version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: budget-db
    restart: always
    environment:
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_pass
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
